# -*- coding: utf-8 -*-
"""IML 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ehv1EODm_Bl_e1mShmaOH-ShWtzY1ldP
"""

from google.colab import files


uploaded = files.upload()

import numpy as np
import pandas as pd
data=pd.read_csv('rainy.csv')
data.head()

concepts = np.array(data)[:,:-1]
concepts

target = np.array(data)[:,-1]
target

def train(con,tar):
    for i,val in enumerate(tar):
        if val=='yes':
            specific_h =  con[i].copy()
            break
    for i,val in enumerate(con):
        if tar[i]=='yes':
            for x in range(len(specific_h)):
                if val[x] != specific_h[x]:
                    specific_h[x] = '?'
                else:
                    pass
    return specific_h

print(train(concepts,target))

from google.colab import files


uploaded = files.upload()

import numpy as np
import pandas as pd
data=pd.read_csv('expensive.csv')
data.head()

concepts = np.array(data)[:,:-1]
concepts

target = np.array(data)[:,-1]
target

def train(con,tar):
    for i,val in enumerate(tar):
        if val=='yes':
            specific_h =  con[i].copy()
            break
    for i,val in enumerate(con):
        if tar[i]=='yes':
            for x in range(len(specific_h)):
                if val[x] != specific_h[x]:
                    specific_h[x] = '?'
                else:
                    pass
    return specific_h

print(train(concepts,target))

